### ISSUE TITLE
Alias for cgrep

### ISSUE THREAD

**Issue by alexandernst** [awgn/cgrep#12]
Currently cgrep collides with `cgrep` from https://sourceforge.net/projects/cgrep/ . Maybe make the binary compile to `cagrep` (as in Context-Aware grep) or some other alias?

**Comment by alexandernst** [comment]
Why did this get closed? Is still applies to current verison, even if the original bug report is from 2014.

**Comment by awgn** [comment]
Because it must be a regression due to some recent refactoring.

However I closed the ticket by error... Please reopen it.



On Fri, Oct 30, 2015 at 12:52 PM, Alexander Nestorov <
notifications@github.com> wrote:

> Why did this get closed? Is still applies to current verison, even if the
> original bug report is from 2014.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/awgn/cgrep/issues/12#issuecomment-152505029>.
>



-- 
The difference between theory and practice is bigger in practice than in
theory.

**Comment by alexandernst** [comment]
I can't re-open a ticket closed by the repo owner (you).
